package com.inktrack.infrastructure.gateway;

import com.inktrack.InkTrackApplication;
import com.inktrack.core.domain.User;
import com.inktrack.infrastructure.entity.UserEntity;
import com.inktrack.infrastructure.mapper.UserMapper;
import com.inktrack.infrastructure.persistence.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest(classes = InkTrackApplication.class)
@ActiveProfiles("test")
@Transactional
class UserGatewayIntegrationTest {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private UserMapper userMapper;

    private UserGatewayImp userGateway;

    @BeforeEach
    void setUp() {
        userGateway = new UserGatewayImp(userRepository, userMapper);
        userRepository.deleteAll();
    }

    @Test
    void shouldSaveUserAndRetrieveByEmail() {
        User user = new User(null, "John Doe", "john@example.com", "hashed_password", LocalDateTime.now());

        User savedUser = userGateway.save(user);

        assertNotNull(savedUser.getId());
        assertEquals("John Doe", savedUser.getName());
        assertEquals("john@example.com", savedUser.getEmail());

        Optional<User> retrievedUser = userGateway.findByEmail("john@example.com");
        assertTrue(retrievedUser.isPresent());
        assertEquals(savedUser.getId(), retrievedUser.get().getId());
        assertEquals("John Doe", retrievedUser.get().getName());
    }

    @Test
    void shouldReturnEmptyWhenUserNotFound() {
        Optional<User> result = userGateway.findByEmail("nonexistent@example.com");

        assertTrue(result.isEmpty());
    }

    @Test
    void shouldPersistUserWithAutoGeneratedId() {
        User user = new User(null, "Jane Doe", "jane@example.com", "hashed_password", LocalDateTime.now());

        User savedUser = userGateway.save(user);

        assertNotNull(savedUser.getId(), "ID should be auto-generated");
        
        Optional<UserEntity> entityInDb = userRepository.findById(savedUser.getId());
        assertTrue(entityInDb.isPresent());
        assertEquals("Jane Doe", entityInDb.get().getName());
    }

    @Test
    void shouldPersistCreatedAtTimestamp() {
        User user = new User(null, "Bob Smith", "bob@example.com", "hashed_password", LocalDateTime.now());

        User savedUser = userGateway.save(user);

        assertNotNull(savedUser.getCreatedAt());
        
        Optional<UserEntity> entityInDb = userRepository.findById(savedUser.getId());
        assertTrue(entityInDb.isPresent());
        assertNotNull(entityInDb.get().getCreatedAt());
    }

    @Test
    void shouldFindMultipleUsersIndependently() {
        User user1 = new User(null, "Alice", "alice@example.com", "pass1", LocalDateTime.now());
        User user2 = new User(null, "Bob", "bob@example.com", "pass2", LocalDateTime.now());

        userGateway.save(user1);
        userGateway.save(user2);

        Optional<User> foundAlice = userGateway.findByEmail("alice@example.com");
        Optional<User> foundBob = userGateway.findByEmail("bob@example.com");

        assertTrue(foundAlice.isPresent());
        assertTrue(foundBob.isPresent());
        assertEquals("Alice", foundAlice.get().getName());
        assertEquals("Bob", foundBob.get().getName());
        assertNotEquals(foundAlice.get().getId(), foundBob.get().getId());
    }
}
