package com.inktrack.infrastructure.gateway;

import com.inktrack.InkTrackApplication;
import com.inktrack.core.domain.User;
import com.inktrack.infrastructure.entity.BookEntity;
import com.inktrack.infrastructure.entity.CategoryEntity;
import com.inktrack.infrastructure.entity.UserEntity;
import com.inktrack.infrastructure.mapper.UserMapper;
import com.inktrack.infrastructure.persistence.BookRepository;
import com.inktrack.infrastructure.persistence.CategoryRepository;
import com.inktrack.infrastructure.persistence.NoteRepository;
import com.inktrack.infrastructure.persistence.ReadingSessionRepository;
import com.inktrack.infrastructure.persistence.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@SpringBootTest(classes = InkTrackApplication.class)
@ActiveProfiles("test")
class UserGatewayIntegrationTest {

  @Autowired
  private UserRepository userRepository;

  @Autowired
  private UserMapper userMapper;

  @Autowired
  private BookRepository bookRepository;

  @Autowired
  private NoteRepository noteRepository;

  @Autowired
  private ReadingSessionRepository readingSessionRepository;

  @Autowired
  private CategoryRepository categoryRepository;

  private UserGatewayImpl userGateway;

  @BeforeEach
  void setUp() {
    userGateway = new UserGatewayImpl(userRepository, userMapper);
  }

  @BeforeEach
  void cleanDatabase() {
    noteRepository.deleteAllInBatch();
    readingSessionRepository.deleteAllInBatch();
    bookRepository.deleteAllInBatch();
    userRepository.deleteAllInBatch();
    categoryRepository.deleteAllInBatch();
  }

  @Test
  void shouldSaveUserAndRetrieveByEmail() {
    User user = new User(null, "John Doe", "john@example.com", "hashed_password", LocalDateTime.now());

    User savedUser = userGateway.save(user);

    assertNotNull(savedUser.getId());
    assertEquals("John Doe", savedUser.getName());
    assertEquals("john@example.com", savedUser.getEmail());

    Optional<User> retrievedUser = userGateway.findByEmail("john@example.com");
    assertTrue(retrievedUser.isPresent());
    assertEquals(savedUser.getId(), retrievedUser.get().getId());
    assertEquals("John Doe", retrievedUser.get().getName());
  }

  @Test
  void shouldReturnEmptyWhenUserNotFound() {
    Optional<User> result = userGateway.findByEmail("nonexistent@example.com");

    assertTrue(result.isEmpty());
  }

  @Test
  void shouldPersistUserWithAutoGeneratedId() {
    User user = new User(null, "Jane Doe", "jane@example.com", "hashed_password", LocalDateTime.now());

    User savedUser = userGateway.save(user);

    assertNotNull(savedUser.getId(), "ID should be auto-generated");

    Optional<UserEntity> entityInDb = userRepository.findById(savedUser.getId());
    assertTrue(entityInDb.isPresent());
    assertEquals("Jane Doe", entityInDb.get().getName());
  }

  @Test
  void shouldPersistCreatedAtTimestamp() {
    User user = new User(null, "Bob Smith", "bob@example.com", "hashed_password", LocalDateTime.now());

    User savedUser = userGateway.save(user);

    assertNotNull(savedUser.getCreatedAt());

    Optional<UserEntity> entityInDb = userRepository.findById(savedUser.getId());
    assertTrue(entityInDb.isPresent());
    assertNotNull(entityInDb.get().getCreatedAt());
  }

  @Test
  void shouldFindMultipleUsersIndependently() {
    User user1 = new User(null, "Alice", "alice@example.com", "pass1", LocalDateTime.now());
    User user2 = new User(null, "Bob", "bob@example.com", "pass2", LocalDateTime.now());

    userGateway.save(user1);
    userGateway.save(user2);

    Optional<User> foundAlice = userGateway.findByEmail("alice@example.com");
    Optional<User> foundBob = userGateway.findByEmail("bob@example.com");

    assertTrue(foundAlice.isPresent());
    assertTrue(foundBob.isPresent());
    assertEquals("Alice", foundAlice.get().getName());
    assertEquals("Bob", foundBob.get().getName());
    assertNotEquals(foundAlice.get().getId(), foundBob.get().getId());
  }

  @Test
  void shouldFindUserById() {
    User user = new User(null, "John Doe", "john@example.com", "hashed_password", LocalDateTime.now());

    User savedUser = userGateway.save(user);

    Optional<User> retrievedUser = userGateway.findById(savedUser.getId());
    assertTrue(retrievedUser.isPresent());
    assertEquals(savedUser.getId(), retrievedUser.get().getId());
    assertEquals("John Doe", retrievedUser.get().getName());
  }

  @Test
  void shouldReturnEmptyWhenUserNotFoundById() {
    Optional<User> result = userGateway.findById(UUID.randomUUID());

    assertTrue(result.isEmpty());
  }

  @Test
  void shouldUpdateUserData() {
    User user = new User(null, "John Doe", "john@example.com", "hashed_password", LocalDateTime.now());
    User savedUser = userGateway.save(user);

    User updatedUser = new User(
        savedUser.getId(),
        "John Doe Updated",
        "john.updated@example.com",
        "new_hashed_password",
        savedUser.getCreatedAt()
    );

    User result = userGateway.update(updatedUser);

    assertEquals("John Doe Updated", result.getName());
    assertEquals("john.updated@example.com", result.getEmail());

    Optional<User> retrieved = userGateway.findById(savedUser.getId());
    assertTrue(retrieved.isPresent());
    assertEquals("John Doe Updated", retrieved.get().getName());
    assertEquals("john.updated@example.com", retrieved.get().getEmail());
    assertEquals("new_hashed_password", retrieved.get().getPassword());

    Optional<User> oldEmail = userGateway.findByEmail("john@example.com");
    assertTrue(oldEmail.isEmpty());
  }

  @Test
  void shouldDeleteUserAndCascadeBooks() {
    User user = new User(null, "John Doe", "john@example.com", "hashed_password", LocalDateTime.now());
    User savedUser = userGateway.save(user);

    CategoryEntity category = categoryRepository.save(new CategoryEntity(null, "Fiction", OffsetDateTime.now()));

    UserEntity userEntity = userRepository.findById(savedUser.getId()).orElseThrow();
    BookEntity book = BookEntity.builder()
        .user(userEntity)
        .category(category)
        .title("Book Title")
        .author("Author")
        .totalPages(100)
        .pagesRead(0)
        .progress(0)
        .build();
    bookRepository.save(book);

    userGateway.deleteById(savedUser.getId());

    assertTrue(userRepository.findById(savedUser.getId()).isEmpty());
    assertEquals(0, bookRepository.count());
  }
}
