INSERT INTO public.tb_categories (name)
VALUES ('OTHER'),
       ('FICTION'),
       ('NON_FICTION'),
       ('FANTASY'),
       ('SCIENCE_FICTION'),
       ('MYSTERY'),
       ('THRILLER'),
       ('ROMANCE'),
       ('HORROR'),
       ('BIOGRAPHY'),
       ('HISTORY'),
       ('SELF_HELP'),
       ('BUSINESS'),
       ('TECHNOLOGY'),
       ('EDUCATION'),
       ('PHILOSOPHY'),
       ('PSYCHOLOGY'),
       ('RELIGION'),
       ('COMICS'),
       ('CHILDREN'),
       ('YOUNG_ADULT');
